### ISSUE TITLE
Doesn't support non-HTTPS connections to OpenStack

### ISSUE THREAD

**Issue by fifieldt** [ngasiproj/caimito#1]
Thanks for your project :)

I notice the default configuration file uses https to contact OpenStack in the cloud.url parameter.

cloud.url=https://....:5000/auth/v1.0/

If you try to use http, here's what happens:

java.lang.IllegalStateException: Scheme 'http' not registered.
    at org.apache.http.conn.scheme.SchemeRegistry.getScheme(SchemeRegistry.java:73)
    at org.apache.http.impl.conn.DefaultHttpRoutePlanner.determineRoute(DefaultHttpRoutePlanner.java:111)
    at org.apache.http.impl.client.DefaultRequestDirector.determineRoute(DefaultRequestDirector.java:655)
    at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:353)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:641)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:576)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:554)
    at tools.util.HttpClientUtil.trustNVGet(HttpClientUtil.java:1402)
    at tools.util.HttpClientUtil.trustGet(HttpClientUtil.java:1220)
    at tools.util.HttpClientUtil.trustGet(HttpClientUtil.java:1203)
    at tools.util.HttpClientUtil.trustGet(HttpClientUtil.java:1154)
    at tools.util.HttpClientUtil.trustGet(HttpClientUtil.java:941)
    at ngasi.caimito.resource.OpenStackResourceObj.auth(OpenStackResourceObj.java:481)
    at ngasi.caimito.resource.OpenStackResourceObj.doList(OpenStackResourceObj.java:501)
    at ngasi.caimito.resource.ResourceObj.list(ResourceObj.java:117)
    at ngasi.caimito.CaimitoDefaultServlet.renderHtml(CaimitoDefaultServlet.java:1542)
    at ngasi.caimito.CaimitoDefaultServlet.render(CaimitoDefaultServlet.java:1338)
    at ngasi.caimito.CaimitoDefaultServlet.serveResource(CaimitoDefaultServlet.java:1034)
    at ngasi.caimito.CaimitoDefaultServlet.doGet(CaimitoDefaultServlet.java:477)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
    at ngasi.caimito.CaimitoWebdavServlet.service(CaimitoWebdavServlet.java:414)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.shaft.ShaftFilter.doFilter(ShaftFilter.java:204)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:225)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:169)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:927)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:999)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:565)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:309)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:679)
ngasi.caimito.CaimitoException: java.lang.IllegalStateException: Scheme 'http' not registered.
    at ngasi.caimito.CaimitoException.throwException(CaimitoException.java:56)
    at ngasi.caimito.resource.OpenStackResourceObj.auth(OpenStackResourceObj.java:491)
    at ngasi.caimito.resource.OpenStackResourceObj.doList(OpenStackResourceObj.java:501)
    at ngasi.caimito.resource.ResourceObj.list(ResourceObj.java:117)
    at ngasi.caimito.CaimitoDefaultServlet.renderHtml(CaimitoDefaultServlet.java:1542)
    at ngasi.caimito.CaimitoDefaultServlet.render(CaimitoDefaultServlet.java:1338)
    at ngasi.caimito.CaimitoDefaultServlet.serveResource(CaimitoDefaultServlet.java:1034)
    at ngasi.caimito.CaimitoDefaultServlet.doGet(CaimitoDefaultServlet.java:477)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
    at ngasi.caimito.CaimitoWebdavServlet.service(CaimitoWebdavServlet.java:414)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.shaft.ShaftFilter.doFilter(ShaftFilter.java:204)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:225)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:169)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:927)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:999)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:565)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:309)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:679)

**Comment by ngasiproj** [comment]
Hi Tom,
Do you have a publicly accessibly HTTP container I can test against?

Regards

-----Original Message-----
From: "Tom Fifield" reply@reply.github.com
Sent: Wednesday, May 30, 2012 9:47pm
To: "ngasiproj" gabrielw@ngasi.com
Subject: [caimito] Doesn't support non-HTTPS connections to OpenStack (#1)

Thanks for your project :)

I notice the default configuration file uses https to contact OpenStack in the cloud.url parameter.

cloud.url=https://....:5000/auth/v1.0/

If you try to use http, here's what happens:

java.lang.IllegalStateException: Scheme 'http' not registered.
 at org.apache.http.conn.scheme.SchemeRegistry.getScheme(SchemeRegistry.java:73)
 at org.apache.http.impl.conn.DefaultHttpRoutePlanner.determineRoute(DefaultHttpRoutePlanner.java:111)
 at org.apache.http.impl.client.DefaultRequestDirector.determineRoute(DefaultRequestDirector.java:655)
 at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:353)
 at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:641)
 at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:576)
 at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:554)
 at tools.util.HttpClientUtil.trustNVGet(HttpClientUtil.java:1402)
 at tools.util.HttpClientUtil.trustGet(HttpClientUtil.java:1220)
 at tools.util.HttpClientUtil.trustGet(HttpClientUtil.java:1203)
 at tools.util.HttpClientUtil.trustGet(HttpClientUtil.java:1154)
 at tools.util.HttpClientUtil.trustGet(HttpClientUtil.java:941)
 at ngasi.caimito.resource.OpenStackResourceObj.auth(OpenStackResourceObj.java:481)
 at ngasi.caimito.resource.OpenStackResourceObj.doList(OpenStackResourceObj.java:501)
 at ngasi.caimito.resource.ResourceObj.list(ResourceObj.java:117)
 at ngasi.caimito.CaimitoDefaultServlet.renderHtml(CaimitoDefaultServlet.java:1542)
 at ngasi.caimito.CaimitoDefaultServlet.render(CaimitoDefaultServlet.java:1338)
 at ngasi.caimito.CaimitoDefaultServlet.serveResource(CaimitoDefaultServlet.java:1034)
 at ngasi.caimito.CaimitoDefaultServlet.doGet(CaimitoDefaultServlet.java:477)
 at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
 at ngasi.caimito.CaimitoWebdavServlet.service(CaimitoWebdavServlet.java:414)
 at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
 at org.shaft.ShaftFilter.doFilter(ShaftFilter.java:204)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
 at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:225)
 at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:169)
 at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)
 at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
 at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:927)
 at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
 at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
 at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:999)
 at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:565)
 at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:309)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
 at java.lang.Thread.run(Thread.java:679)
ngasi.caimito.CaimitoException: java.lang.IllegalStateException: Scheme 'http' not registered.
 at ngasi.caimito.CaimitoException.throwException(CaimitoException.java:56)
 at ngasi.caimito.resource.OpenStackResourceObj.auth(OpenStackResourceObj.java:491)
 at ngasi.caimito.resource.OpenStackResourceObj.doList(OpenStackResourceObj.java:501)
 at ngasi.caimito.resource.ResourceObj.list(ResourceObj.java:117)
 at ngasi.caimito.CaimitoDefaultServlet.renderHtml(CaimitoDefaultServlet.java:1542)
 at ngasi.caimito.CaimitoDefaultServlet.render(CaimitoDefaultServlet.java:1338)
 at ngasi.caimito.CaimitoDefaultServlet.serveResource(CaimitoDefaultServlet.java:1034)
 at ngasi.caimito.CaimitoDefaultServlet.doGet(CaimitoDefaultServlet.java:477)
 at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
 at ngasi.caimito.CaimitoWebdavServlet.service(CaimitoWebdavServlet.java:414)
 at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
 at org.shaft.ShaftFilter.doFilter(ShaftFilter.java:204)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
 at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:225)
 at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:169)
 at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)
 at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
 at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:927)
 at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
 at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
 at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:999)
 at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:565)
 at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:309)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
 at java.lang.Thread.run(Thread.java:679)

---

Reply to this email directly or view it on GitHub:
https://github.com/ngasiproj/caimito/issues/1

**Comment by ngasiproj** [comment]
Hi Tom,

I have pushed an update that should fix your problem.

**Comment by fifieldt** [comment]
Thanks, that fixes this problem
