### ISSUE TITLE
Doesn't support OpenStack Keystone API 2.0 ?

### ISSUE THREAD

**Issue by fifieldt** [ngasiproj/caimito#2]
Thanks for your project :)

I notice the default configuration file uses version 1.0 to contact OpenStack in the cloud.url parameter.

cloud.url=https://....:5000/auth/v1.0/

If you try to use 2.0 (eg cloud.url=http://keystone.rc.nectar.org.au:5000/v2.0/) , here's what happens:

java.lang.NullPointerException
    at java.util.Hashtable.put(Hashtable.java:411)
    at ngasi.caimito.resource.OpenStackResourceObj.doList(OpenStackResourceObj.java:504)
    at ngasi.caimito.resource.ResourceObj.list(ResourceObj.java:117)
    at ngasi.caimito.CaimitoDefaultServlet.renderHtml(CaimitoDefaultServlet.java:1542)
    at ngasi.caimito.CaimitoDefaultServlet.render(CaimitoDefaultServlet.java:1338)
    at ngasi.caimito.CaimitoDefaultServlet.serveResource(CaimitoDefaultServlet.java:1034)
    at ngasi.caimito.CaimitoDefaultServlet.doGet(CaimitoDefaultServlet.java:477)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
    at ngasi.caimito.CaimitoWebdavServlet.service(CaimitoWebdavServlet.java:414)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.shaft.ShaftFilter.doFilter(ShaftFilter.java:204)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:225)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:169)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:927)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:999)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:565)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:307)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:679)
java.lang.NullPointerException
    at java.util.Hashtable.put(Hashtable.java:411)
    at ngasi.caimito.resource.OpenStackResourceObj.doList(OpenStackResourceObj.java:504)
    at ngasi.caimito.resource.ResourceObj.list(ResourceObj.java:117)
    at ngasi.caimito.CaimitoDefaultServlet.renderHtml(CaimitoDefaultServlet.java:1542)
    at ngasi.caimito.CaimitoDefaultServlet.render(CaimitoDefaultServlet.java:1338)
    at ngasi.caimito.CaimitoDefaultServlet.serveResource(CaimitoDefaultServlet.java:1034)
    at ngasi.caimito.CaimitoDefaultServlet.doGet(CaimitoDefaultServlet.java:477)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
    at ngasi.caimito.CaimitoWebdavServlet.service(CaimitoWebdavServlet.java:414)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.shaft.ShaftFilter.doFilter(ShaftFilter.java:204)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:225)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:169)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:927)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:999)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:565)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:309)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:679)

Here is the packet and response:

GET /v2.0/ HTTP/1.1
X-Auth-Key: [secret key]
X-Auth-User: [username]
Host: [keystone hostname]:5000
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.0.1 (java 1.5)

HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8
Content-Length: 1225
Date: Fri, 01 Jun 2012 01:42:24 GMT
Connection: keep-alive

{
    "version" : {
        "id" : "v2.0",
        "status" : "ALPHA",
        "updated" : "2011-11-19T00:00:00Z",
        "links": [
            {
                "rel" : "self",
                "href" : "http://115.146.90.154:5000/v2.0/"
            },
            {
                "rel" : "describedby",
                "type" : "text/html",
                "href" : "http://docs.openstack.org/api/openstack-identity-service/2.0/content/"
            },
            {
                "rel" : "describedby",
                "type" : "application/pdf",
                "href" : "http://docs.openstack.org/api/openstack-identity-service/2.0/identity-dev-guide-2.0.pdf"
            },
            {
                "rel" : "describedby",
                "type" : "application/vnd.sun.wadl+xml",
                "href" : "http://115.146.90.154:5000/v2.0/identity.wadl"
            }
        ],
        "media-types": [
            {
                "base" : "application/xml",
                "type" : "application/vnd.openstack.identity-v2.0+xml"
            },
            {
                "base" : "application/json",
                "type" : "application/vnd.openstack.identity-v2.0+json"
            }
        ]
    }
}

**Comment by ngasiproj** [comment]
Hi Tom,
Caimito has not yet been tested against 2.0. But you can help by giving me access...
Regards

-----Original Message-----
From: "Tom Fifield" reply@reply.github.com
Sent: Thursday, May 31, 2012 9:51pm
To: "ngasiproj" gabrielw@ngasi.com
Subject: [caimito] Doesn't support OpenStack Keystone API 2.0 ? (#2)

Thanks for your project :)

I notice the default configuration file uses version 1.0 to contact OpenStack in the cloud.url parameter.

cloud.url=https://....:5000/auth/v1.0/

If you try to use 2.0 (eg cloud.url=http://keystone.rc.nectar.org.au:5000/v2.0/) , here's what happens:

java.lang.NullPointerException
 at java.util.Hashtable.put(Hashtable.java:411)
 at ngasi.caimito.resource.OpenStackResourceObj.doList(OpenStackResourceObj.java:504)
 at ngasi.caimito.resource.ResourceObj.list(ResourceObj.java:117)
 at ngasi.caimito.CaimitoDefaultServlet.renderHtml(CaimitoDefaultServlet.java:1542)
 at ngasi.caimito.CaimitoDefaultServlet.render(CaimitoDefaultServlet.java:1338)
 at ngasi.caimito.CaimitoDefaultServlet.serveResource(CaimitoDefaultServlet.java:1034)
 at ngasi.caimito.CaimitoDefaultServlet.doGet(CaimitoDefaultServlet.java:477)
 at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
 at ngasi.caimito.CaimitoWebdavServlet.service(CaimitoWebdavServlet.java:414)
 at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
 at org.shaft.ShaftFilter.doFilter(ShaftFilter.java:204)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
 at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:225)
 at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:169)
 at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)
 at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
 at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:927)
 at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
 at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
 at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:999)
 at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:565)
 at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:307)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
 at java.lang.Thread.run(Thread.java:679)
java.lang.NullPointerException
 at java.util.Hashtable.put(Hashtable.java:411)
 at ngasi.caimito.resource.OpenStackResourceObj.doList(OpenStackResourceObj.java:504)
 at ngasi.caimito.resource.ResourceObj.list(ResourceObj.java:117)
 at ngasi.caimito.CaimitoDefaultServlet.renderHtml(CaimitoDefaultServlet.java:1542)
 at ngasi.caimito.CaimitoDefaultServlet.render(CaimitoDefaultServlet.java:1338)
 at ngasi.caimito.CaimitoDefaultServlet.serveResource(CaimitoDefaultServlet.java:1034)
 at ngasi.caimito.CaimitoDefaultServlet.doGet(CaimitoDefaultServlet.java:477)
 at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
 at ngasi.caimito.CaimitoWebdavServlet.service(CaimitoWebdavServlet.java:414)
 at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
 at org.shaft.ShaftFilter.doFilter(ShaftFilter.java:204)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
 at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:225)
 at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:169)
 at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)
 at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
 at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:927)
 at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
 at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
 at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:999)
 at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:565)
 at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:309)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
 at java.lang.Thread.run(Thread.java:679)

Here is the packet and response:

GET /v2.0/ HTTP/1.1
X-Auth-Key: <secret key>
X-Auth-User: <username>
Host: <keystone hostname>:5000
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.0.1 (java 1.5)

HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8
Content-Length: 1225
Date: Fri, 01 Jun 2012 01:42:24 GMT
Connection: keep-alive

{
 "version" : {
 "id" : "v2.0",
 "status" : "ALPHA",
 "updated" : "2011-11-19T00:00:00Z",
 "links": [
 {
 "rel" : "self",
 "href" : "http://115.146.90.154:5000/v2.0/"
 },
 {
 "rel" : "describedby",
 "type" : "text/html",
 "href" : "http://docs.openstack.org/api/openstack-identity-service/2.0/content/"
 },
 {
 "rel" : "describedby",
 "type" : "application/pdf",
 "href" : "http://docs.openstack.org/api/openstack-identity-service/2.0/identity-dev-guide-2.0.pdf"
 },
 {
 "rel" : "describedby",
 "type" : "application/vnd.sun.wadl+xml",
 "href" : "http://115.146.90.154:5000/v2.0/identity.wadl"
 }
 ],
 "media-types": [
 {
 "base" : "application/xml",
 "type" : "application/vnd.openstack.identity-v2.0+xml"
 },
 {
 "base" : "application/json",
 "type" : "application/vnd.openstack.identity-v2.0+json"
 }
 ]
 }
}

---

Reply to this email directly or view it on GitHub:
https://github.com/ngasiproj/caimito/issues/2

**Comment by ngasiproj** [comment]
Hi Tom,
The latest Caimito now supports OpenStack API 2.0.
Thanks for your help.
Regards

**Comment by fifieldt** [comment]
I'm getting 
java.lang.TypeNotPresentException: Type ngasi.caimito.resource.OSV2TokenResponse not present

resource=openstack
cloud.store=tfwebdav
cloud.username=[username]
cloud.api.key_password=[password]
cloud.url=http://keystone.rc.nectar.org.au:5000/v2.0
cloud.endpoint.access=public

java.lang.TypeNotPresentException: Type ngasi.caimito.resource.OSV2TokenResponse not present
    at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:116)
    at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125)
    at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
    at sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68)
    at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138)
    at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
    at sun.reflect.generics.repository.ClassRepository.getSuperclass(ClassRepository.java:84)
    at java.lang.Class.getGenericSuperclass(Class.java:694)
    at com.google.gson.reflect.TypeToken.getSuperclassTypeParameter(TypeToken.java:89)
    at com.google.gson.reflect.TypeToken.<init>(TypeToken.java:65)
    at ngasi.caimito.resource.OpenStackResourceObj$1.<init>(OpenStackResourceObj.java:512)
    at ngasi.caimito.resource.OpenStackResourceObj.auth(OpenStackResourceObj.java:512)
    at ngasi.caimito.resource.OpenStackResourceObj.doList(OpenStackResourceObj.java:537)
    at ngasi.caimito.resource.ResourceObj.list(ResourceObj.java:117)
    at ngasi.caimito.CaimitoDefaultServlet.renderHtml(CaimitoDefaultServlet.java:1543)
    at ngasi.caimito.CaimitoDefaultServlet.render(CaimitoDefaultServlet.java:1338)
    at ngasi.caimito.CaimitoDefaultServlet.serveResource(CaimitoDefaultServlet.java:1034)
    at ngasi.caimito.CaimitoDefaultServlet.doGet(CaimitoDefaultServlet.java:477)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
    at ngasi.caimito.CaimitoWebdavServlet.service(CaimitoWebdavServlet.java:413)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.shaft.ShaftFilter.doFilter(ShaftFilter.java:204)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:225)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:169)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:927)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:999)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:565)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:307)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:679)
Caused by: java.lang.ClassNotFoundException: ngasi.caimito.resource.OSV2TokenResponse
    at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1711)
    at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1556)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:113)
    ... 38 more
ngasi.caimito.CaimitoException: java.lang.TypeNotPresentException: Type ngasi.caimito.resource.OSV2TokenResponse not present
    at ngasi.caimito.CaimitoException.throwException(CaimitoException.java:56)
    at ngasi.caimito.resource.OpenStackResourceObj.auth(OpenStackResourceObj.java:527)
    at ngasi.caimito.resource.OpenStackResourceObj.doList(OpenStackResourceObj.java:537)
    at ngasi.caimito.resource.ResourceObj.list(ResourceObj.java:117)
    at ngasi.caimito.CaimitoDefaultServlet.renderHtml(CaimitoDefaultServlet.java:1543)
    at ngasi.caimito.CaimitoDefaultServlet.render(CaimitoDefaultServlet.java:1338)
    at ngasi.caimito.CaimitoDefaultServlet.serveResource(CaimitoDefaultServlet.java:1034)
    at ngasi.caimito.CaimitoDefaultServlet.doGet(CaimitoDefaultServlet.java:477)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
    at ngasi.caimito.CaimitoWebdavServlet.service(CaimitoWebdavServlet.java:413)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.shaft.ShaftFilter.doFilter(ShaftFilter.java:204)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:225)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:169)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:927)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:999)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:565)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:307)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:679)

Here's the HTTP:

POST /v2.0/tokens HTTP/1.1
Content-type: application/json
Transfer-Encoding: chunked
Host: keystone.rc.nectar.org.au:5000
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.0.1 (java 1.5)
Expect: 100-Continue

69
{"auth":{"passwordCredentials":{"password":"[password]","username":"[username]"}}}
0

HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8
Content-Length: 1428
Date: Wed, 06 Jun 2012 01:00:26 GMT
Connection: keep-alive

{"access": {"token": {"expires": "2012-06-07T10:44:04", "id": "[token]", "tenant": {"id": "25", "name": "pt-27"}}, "serviceCatalog": [{"endpoints": [{"adminURL": "http://keystone.rc.nectar.org.au:35357/v2.0", "region": "Melbourne", "internalURL": "http://keystone.rc.nectar.org.au:5000/v2.0", "publicURL": "http://keystone.rc.nectar.org.au:5000/v2.0"}], "type": "identity", "name": "keystone"}, {"endpoints": [{"adminURL": "http://swift.rc.nectar.org.au:8888/v1.0/", "region": "Melbourne", "internalURL": "http://swift.rc.nectar.org.au:8888/v1/AUTH_25", "publicURL": "http://swift.rc.nectar.org.au:8888/v1/AUTH_25"}], "type": "object-store", "name": "swift"}, {"endpoints": [{"adminURL": "http://nova.rc.nectar.org.au:8774/v1.1/25", "region": "Melbourne", "internalURL": "http://nova.rc.nectar.org.au:8774/v1.1/25", "publicURL": "http://nova.rc.nectar.org.au:8774/v1.1/25"}], "type": "compute", "name": "nova"}, {"endpoints": [{"adminURL": "http://np-rcp1.melbourne.nectar.org.au:9292/v1", "region": "Melbourne", "internalURL": "http://np-rcp1.melbourne.nectar.org.au:9292/v1", "publicURL": "http://np-rcp1.melbourne.nectar.org.au:9292/v1"}], "type": "image", "name": "glance"}], "user": {"id": "27", "roles": [{"tenantId": "25", "id": "6", "name": "netadmin"}, {"tenantId": "25", "id": "5", "name": "sysadmin"}, {"tenantId": "25", "id": "2", "name": "Member"}], "name": "[username]"}}}

**Comment by ngasiproj** [comment]
Apologies. Do another pull please.

-----Original Message-----

**Comment by fifieldt** [comment]
It works!

**Comment by ngasiproj** [comment]
Excellent (tried Skyping but I think perhaps I got the wrong contact).

-----Original Message-----

**Comment by mfortin** [comment]
It doesn't always work. The tenantName was left out of the authentication. In my case, I need to specify it to get a valid endpoint.

Easy fix: OpenStackResourceObj.java

497                 Hashtable<String,String> pc = new Hashtable<String,String>();
498                 String[] username = CaimitoConfig.getConfig().getString("cloud.username").split(":");
499                 pc.put("username",username[1]);
500                 pc.put("password",CaimitoConfig.getConfig().getString("cloud.api.key_password"));
501 
502                 Hashtable<String,Hashtable<String,String>> auh = new Hashtable<String,Hashtable<String,String>>();
503                 auh.put("passwordCredentials",pc);
504                 auh.put("tenantName",username[0]);
505 
506                 Hashtable tl = new Hashtable();
507                 tl.put("auth",auh);

This worked for me.

**Comment by ngasiproj** [comment]
Hi mfortin,
Could you elaborate some more
1)What version/build of openstack are you using?
2) So you are saying  on the same openstack instance, authentication SOMETIMES works with the user and tenant name combined. BUT it ALWAYS works when they are split up?

Thanks.
Gabe

-----Original Message-----

**Comment by mfortin** [comment]
Sure.

1) I am using the latest build, I issued a git clone of your repository.
2) tenantName or tenantId had to be specified in my case. Otherwise it
wouldn't work.
Sample code:

without tenantName:
~# curl -X POST -H 'Content-type: application/json' -d '{"auth":
{"passwordCredentials":{"username": "testuser", "password": "password"}}}'
http://127.0.0.1:5000/v2.0/tokens
{"access": {"token": {"expires": "2012-09-01T13:53:13Z", "id":
"75786e886ed94c409201a0dfad5c6676"}, "serviceCatalog": {}, "user":
{"username": "testuser", "roles_links": [], "id":
"808a51a4cf8c440288c7127157cf7013", "roles": [], "name": "testuser"}}}

with tenantName:
~# curl -X POST -H 'Content-type: application/json' -d '{"auth":
{"tenantName":"test", "passwordCredentials":{"username": "testuser",
"password": "password"}}}' http://127.0.0.1:5000/v2.0/tokens
{"access": {"token": {"expires": "2012-09-01T13:53:37Z", "id":
"f38256a3d4664c87965f590cd0ed88ff", "tenant": {"enabled": true,
"description": "Test Tenant", "name": "test", "id":
"ab68850288ef4801a281bb38273500dd"}}, "serviceCatalog": [{"endpoints":
[{"adminURL": "https://127.0.0.1/", "region": "regionOne", "internalURL": "
https://127.0.0.1/v1/AUTH_ab68850288ef4801a281bb38273500dd", "publicURL": "
https://127.0.0.1/v1/AUTH_ab68850288ef4801a281bb38273500dd"}],
"endpoints_links": [], "type": "object-store", "name": "swift"},
{"endpoints": [{"adminURL": "http://127.0.0.1:35357/v2.0/", "region":
"regionOne", "internalURL": "http://127.0.0.1:35357/v2.0/", "publicURL": "
https://auth.swift.ovh.net:5000/"}], "endpoints_links": [], "type":
"identity", "name": "keystone"}], "user": {"username": "testuser",
"roles_links": [], "id": "808a51a4cf8c440288c7127157cf7013", "roles":
[{"name": "user"}], "name": "testuser"}, "metadata": {"is_admin": 0,
"roles": ["e8d25c6700eb43f38679a774f0ad1f99"]}}}

When I created my endpoints, I used the %(tenant_id) wildcard.
~# keystone endpoint-list
+----------------------------------+-----------+---------------------------------------------------+---------------------------------------------------+---------------------------------+
|                id                |   region  |
publicurl                     |                    internalurl
       |             adminurl            |
+----------------------------------+-----------+---------------------------------------------------+---------------------------------------------------+---------------------------------+
| 143e97dc94187cbccd4 | regionOne | https://127.0.0.1/v1/AUTH_%(tenant_id)s|
https://127.0.0.1/v1/AUTH_%(tenant_id)s |   https://127.0.0.1/  |
| d5ed830662b6653593f | regionOne |          https://127.0.0.1:5000/
  |            http://127.0.0.1:35357/v2.0/           |
http://127.0.0.1:35357/v2.0/ |
+----------------------------------+-----------+---------------------------------------------------+---------------------------------------------------+---------------------------------+

I said it sometimes works, because someone said it work and it doesn't in
my case. I believe this is when you only have 1 tenant, or when the
endpoint is hardcoded. Only thing for sure, it did work by specifying the
tenantName in the json string.

Hope this helps.

On a second note, we are looking at a webdav frontend for openstack swift.
We would like to use the webdav credentials to authenticate on openstack
and use the end user container. How easy would it be to adapt your code ?

Mathieu Fortin

**Comment by ngasiproj** [comment]
Hi Mathieu,
It is possible something may have change with the various openstack releases. In any case we will
add the option to split user and tenant names in the coming weeks.
With regards to your last query, which one of the following scenarios matches your requirements (sounds like single_cloud_account_with_multiple_storage):
https://github.com/ngasiproj/caimito/issues/7

-----Original Message-----

**Comment by mfortin** [comment]
multiple_configured_cloud_accounts

Is this already available in your code ?!

Mathieu Fortin

**Comment by ngasiproj** [comment]
Hi Mathieu,
Not quite. In order of priority, we are close to releasing support for cloud_accounts_for_administration_only PLUS a web admin UI in about a week.
multiple_configured_cloud_accounts probably won't be available for another month. BUT it is coming.
Gabe

-----Original Message-----

**Comment by ngasiproj** [comment]
Hi,
tenantName/username splitting now included in latest github code.
Regards

-----Original Message-----
