### ISSUE TITLE
Caimito errors with OpenStack Essex?

### ISSUE THREAD

**Issue by fifieldt** [ngasiproj/caimito#6]
Hi,

When I use Caimito with Essex Keystone, I get errors. 

From what I can tell, it tries to go straight to /v2.0 on the keystone server instead of going to /tokens. Perhaps just a problem between v1.0 and v2.0 detection?

Here's what's happening on the HTTP level:

GET /v2.0 HTTP/1.1
X-Auth-Key: [key]
X-Auth-User: [username]
Host: [keystone_host]
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.0.1 (java 1.5)

HTTP/1.1 500 Internal Server Error
Content-Type: text/plain
Content-Length: 4327
Date: Thu, 14 Jun 2012 03:56:51 GMT
Connection: close

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/eventlet/wsgi.py", line 336, in handle_one_response
    result = self.application(self.environ, start_response)
  File "/usr/lib/python2.7/dist-packages/paste/urlmap.py", line 203, in **call**
    return app(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/webob/dec.py", line 147, in **call**
    resp = self.call_func(req, _args, *_self.kwargs)
  File "/usr/lib/python2.7/dist-packages/webob/dec.py", line 210, in call_func
    return self.func(req, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/keystone/common/wsgi.py", line 328, in **call**
    response = request.get_response(self.application)
  File "/usr/lib/python2.7/dist-packages/webob/request.py", line 1086, in get_response
    application, catch_exc_info=False)
  File "/usr/lib/python2.7/dist-packages/webob/request.py", line 1055, in call_application
    app_iter = application(self.environ, start_response)
  File "/usr/lib/python2.7/dist-packages/webob/dec.py", line 147, in **call**
    resp = self.call_func(req, _args, *_self.kwargs)
  File "/usr/lib/python2.7/dist-packages/webob/dec.py", line 210, in call_func
    return self.func(req, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/keystone/common/wsgi.py", line 328, in **call**
    response = request.get_response(self.application)
  File "/usr/lib/python2.7/dist-packages/webob/request.py", line 1086, in get_response
    application, catch_exc_info=False)
  File "/usr/lib/python2.7/dist-packages/webob/request.py", line 1055, in call_application
    app_iter = application(self.environ, start_response)
  File "/usr/lib/python2.7/dist-packages/webob/dec.py", line 147, in **call**
    resp = self.call_func(req, _args, *_self.kwargs)
  File "/usr/lib/python2.7/dist-packages/webob/dec.py", line 210, in call_func
    return self.func(req, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/keystone/common/wsgi.py", line 328, in **call**
    response = request.get_response(self.application)
  File "/usr/lib/python2.7/dist-packages/webob/request.py", line 1086, in get_response
    application, catch_exc_info=False)
  File "/usr/lib/python2.7/dist-packages/webob/request.py", line 1055, in call_application
    app_iter = application(self.environ, start_response)
  File "/usr/lib/python2.7/dist-packages/webob/dec.py", line 147, in **call**
    resp = self.call_func(req, _args, *_self.kwargs)
  File "/usr/lib/python2.7/dist-packages/webob/dec.py", line 210, in call_func
    return self.func(req, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/keystone/common/wsgi.py", line 328, in **call**
    response = request.get_response(self.application)
  File "/usr/lib/python2.7/dist-packages/webob/request.py", line 1086, in get_response
    application, catch_exc_info=False)
  File "/usr/lib/python2.7/dist-packages/webob/request.py", line 1055, in call_application
    app_iter = application(self.environ, start_response)
  File "/usr/lib/python2.7/dist-packages/webob/dec.py", line 147, in **call**
    resp = self.call_func(req, _args, *_self.kwargs)
  File "/usr/lib/python2.7/dist-packages/webob/dec.py", line 210, in call_func
    return self.func(req, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/keystone/common/wsgi.py", line 351, in **call**
    resp = req.get_response(self.application)
  File "/usr/lib/python2.7/dist-packages/webob/request.py", line 1086, in get_response
    application, catch_exc_info=False)
  File "/usr/lib/python2.7/dist-packages/webob/request.py", line 1055, in call_application
    app_iter = application(self.environ, start_response)
  File "/usr/lib/python2.7/dist-packages/webob/dec.py", line 159, in **call**
    return resp(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/routes/middleware.py", line 80, in **call**
    config.environ = environ
  File "/usr/lib/python2.7/dist-packages/routes/**init**.py", line 22, in **setattr**
    self.load_wsgi_environ(value)
  File "/usr/lib/python2.7/dist-packages/routes/**init**.py", line 51, in load_wsgi_environ
    result = mapper.routematch(path)
  File "/usr/lib/python2.7/dist-packages/routes/mapper.py", line 686, in routematch
    raise RoutesException('URL or environ must be provided')
RoutesException: URL or environ must be provided

Caimito log:

ngasi.caimito.CaimitoException: java.lang.Exception: Get Method failed: HTTP/1.1 500 Internal Server Error
        at ngasi.caimito.CaimitoException.throwException(CaimitoException.java:56)
        at ngasi.caimito.resource.OpenStackResourceObj.auth(OpenStackResourceObj.java:527)
        at ngasi.caimito.resource.OpenStackResourceObj.doList(OpenStackResourceObj.java:537)
        at ngasi.caimito.resource.ResourceObj.list(ResourceObj.java:117)
        at ngasi.caimito.CaimitoDefaultServlet.renderHtml(CaimitoDefaultServlet.java:1543)
        at ngasi.caimito.CaimitoDefaultServlet.render(CaimitoDefaultServlet.java:1338)
        at ngasi.caimito.CaimitoDefaultServlet.serveResource(CaimitoDefaultServlet.java:1034)
        at ngasi.caimito.CaimitoDefaultServlet.doGet(CaimitoDefaultServlet.java:477)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
        at ngasi.caimito.CaimitoWebdavServlet.service(CaimitoWebdavServlet.java:413)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.shaft.ShaftFilter.doFilter(ShaftFilter.java:204)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:225)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:169)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:927)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:999)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:565)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:309)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
        at java.lang.Thread.run(Thread.java:679)

**Comment by ngasiproj** [comment]
Hi Tom,
Must be something else going on. At the moment Caimito does no auto detection - it first tries v1 auth, if that fails then V2 token auth is attempted. As always if you let me in I can get a better understanding.
BTW what does the Caimito logs show?

-----Original Message-----
From: "Tom Fifield" reply@reply.github.com
Sent: Thursday, June 14, 2012 12:06am
To: "ngasiproj" gabrielw@ngasi.com
Subject: [caimito] Caimito errors with OpenStack Essex? (#6)

Hi,

When I use Caimito with Essex Keystone, I get errors. 

From what I can tell, it tries to go straight to /v2.0 on the keystone server instead of going to /tokens. Perhaps just a problem between v1.0 and v2.0 detection?

Here's what's happening on the HTTP level:

GET /v2.0 HTTP/1.1
X-Auth-Key: [key]
X-Auth-User: [username]
Host: [keystone_host]
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.0.1 (java 1.5)

HTTP/1.1 500 Internal Server Error
Content-Type: text/plain
Content-Length: 4327
Date: Thu, 14 Jun 2012 03:56:51 GMT
Connection: close

Traceback (most recent call last):
 File "/usr/lib/python2.7/dist-packages/eventlet/wsgi.py", line 336, in handle_one_response
 result = self.application(self.environ, start_response)
 File "/usr/lib/python2.7/dist-packages/paste/urlmap.py", line 203, in **call**
 return app(environ, start_response)
 File "/usr/lib/python2.7/dist-packages/webob/dec.py", line 147, in **call**
 resp = self.call_func(req, _args, *_self.kwargs)
 File "/usr/lib/python2.7/dist-packages/webob/dec.py", line 210, in call_func
 return self.func(req, _args, *_kwargs)
 File "/usr/lib/python2.7/dist-packages/keystone/common/wsgi.py", line 328, in **call**
 response = request.get_response(self.application)
 File "/usr/lib/python2.7/dist-packages/webob/request.py", line 1086, in get_response
 application, catch_exc_info=False)
 File "/usr/lib/python2.7/dist-packages/webob/request.py", line 1055, in call_application
 app_iter = application(self.environ, start_response)
 File "/usr/lib/python2.7/dist-packages/webob/dec.py", line 147, in **call**
 resp = self.call_func(req, _args, *_self.kwargs)
 File "/usr/lib/python2.7/dist-packages/webob/dec.py", line 210, in call_func
 return self.func(req, _args, *_kwargs)
 File "/usr/lib/python2.7/dist-packages/keystone/common/wsgi.py", line 328, in **call**
 response = request.get_response(self.application)
 File "/usr/lib/python2.7/dist-packages/webob/request.py", line 1086, in get_response
 application, catch_exc_info=False)
 File "/usr/lib/python2.7/dist-packages/webob/request.py", line 1055, in call_application
 app_iter = application(self.environ, start_response)
 File "/usr/lib/python2.7/dist-packages/webob/dec.py", line 147, in **call**
 resp = self.call_func(req, _args, *_self.kwargs)
 File "/usr/lib/python2.7/dist-packages/webob/dec.py", line 210, in call_func
 return self.func(req, _args, *_kwargs)
 File "/usr/lib/python2.7/dist-packages/keystone/common/wsgi.py", line 328, in **call**
 response = request.get_response(self.application)
 File "/usr/lib/python2.7/dist-packages/webob/request.py", line 1086, in get_response
 application, catch_exc_info=False)
 File "/usr/lib/python2.7/dist-packages/webob/request.py", line 1055, in call_application
 app_iter = application(self.environ, start_response)
 File "/usr/lib/python2.7/dist-packages/webob/dec.py", line 147, in **call**
 resp = self.call_func(req, _args, *_self.kwargs)
 File "/usr/lib/python2.7/dist-packages/webob/dec.py", line 210, in call_func
 return self.func(req, _args, *_kwargs)
 File "/usr/lib/python2.7/dist-packages/keystone/common/wsgi.py", line 328, in **call**
 response = request.get_response(self.application)
 File "/usr/lib/python2.7/dist-packages/webob/request.py", line 1086, in get_response
 application, catch_exc_info=False)
 File "/usr/lib/python2.7/dist-packages/webob/request.py", line 1055, in call_application
 app_iter = application(self.environ, start_response)
 File "/usr/lib/python2.7/dist-packages/webob/dec.py", line 147, in **call**
 resp = self.call_func(req, _args, *_self.kwargs)
 File "/usr/lib/python2.7/dist-packages/webob/dec.py", line 210, in call_func
 return self.func(req, _args, *_kwargs)
 File "/usr/lib/python2.7/dist-packages/keystone/common/wsgi.py", line 351, in **call**
 resp = req.get_response(self.application)
 File "/usr/lib/python2.7/dist-packages/webob/request.py", line 1086, in get_response
 application, catch_exc_info=False)
 File "/usr/lib/python2.7/dist-packages/webob/request.py", line 1055, in call_application
 app_iter = application(self.environ, start_response)
 File "/usr/lib/python2.7/dist-packages/webob/dec.py", line 159, in **call**
 return resp(environ, start_response)
 File "/usr/lib/python2.7/dist-packages/routes/middleware.py", line 80, in **call**
 config.environ = environ
 File "/usr/lib/python2.7/dist-packages/routes/**init**.py", line 22, in **setattr**
 self.load_wsgi_environ(value)
 File "/usr/lib/python2.7/dist-packages/routes/**init**.py", line 51, in load_wsgi_environ
 result = mapper.routematch(path)
 File "/usr/lib/python2.7/dist-packages/routes/mapper.py", line 686, in routematch
 raise RoutesException('URL or environ must be provided')
RoutesException: URL or environ must be provided

Caimito log:

ngasi.caimito.CaimitoException: java.lang.Exception: Get Method failed: HTTP/1.1 500 Internal Server Error
 at ngasi.caimito.CaimitoException.throwException(CaimitoException.java:56)
 at ngasi.caimito.resource.OpenStackResourceObj.auth(OpenStackResourceObj.java:527)
 at ngasi.caimito.resource.OpenStackResourceObj.doList(OpenStackResourceObj.java:537)
 at ngasi.caimito.resource.ResourceObj.list(ResourceObj.java:117)
 at ngasi.caimito.CaimitoDefaultServlet.renderHtml(CaimitoDefaultServlet.java:1543)
 at ngasi.caimito.CaimitoDefaultServlet.render(CaimitoDefaultServlet.java:1338)
 at ngasi.caimito.CaimitoDefaultServlet.serveResource(CaimitoDefaultServlet.java:1034)
 at ngasi.caimito.CaimitoDefaultServlet.doGet(CaimitoDefaultServlet.java:477)
 at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
 at ngasi.caimito.CaimitoWebdavServlet.service(CaimitoWebdavServlet.java:413)
 at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
 at org.shaft.ShaftFilter.doFilter(ShaftFilter.java:204)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
 at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:225)
 at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:169)
 at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)
 at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
 at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:927)
 at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
 at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
 at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:999)
 at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:565)
 at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:309)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
 at java.lang.Thread.run(Thread.java:679)

---

Reply to this email directly or view it on GitHub:
https://github.com/ngasiproj/caimito/issues/6

**Comment by fifieldt** [comment]
Ah yup - that's kinda what I meant. 

In OpenStackResourceObj:auth() I think the v1 call is coming back with a HTTP 500 on the GET, which causes a CaimitoException to be thrown. Due to this, it doesn't fall through to the v2 call, but instead bails out of the method. I think this is happening because the return code has changed between Diablo and Essex. The Caimito trace is above.

So I think if you catch around the V1 and V2 separately, that should work better. Alternately you could add another configuration flag to use V2 auth only ...

**Comment by ngasiproj** [comment]
Hi Tom,
Please pull the latest and let me know how it goes.
Regards

-----Original Message-----

**Comment by fifieldt** [comment]
If I configure the api=2.0 I get a NullPointerException, and no request gets sent to swift

ngasi.caimito.CaimitoException: java.lang.NullPointerException
        at ngasi.caimito.CaimitoException.throwException(CaimitoException.java:56)
        at ngasi.caimito.resource.OpenStackResourceObj.auth(OpenStackResourceObj.java:525)
        at ngasi.caimito.resource.OpenStackResourceObj.doList(OpenStackResourceObj.java:535)
        at ngasi.caimito.resource.ResourceObj.list(ResourceObj.java:117)
        at ngasi.caimito.CaimitoWebdavServlet.doPropfind(CaimitoWebdavServlet.java:738)
        at ngasi.caimito.CaimitoWebdavServlet.service(CaimitoWebdavServlet.java:398)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.shaft.ShaftFilter.doFilter(ShaftFilter.java:204)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:225)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:169)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:927)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:999)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:565)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:309)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
        at java.lang.Thread.run(Thread.java:679)
ngasi.caimito.CaimitoException: java.lang.NullPointerException
        at ngasi.caimito.CaimitoException.throwException(CaimitoException.java:56)
        at ngasi.caimito.resource.OpenStackResourceObj.auth(OpenStackResourceObj.java:525)
        at ngasi.caimito.resource.OpenStackResourceObj.doList(OpenStackResourceObj.java:535)
        at ngasi.caimito.resource.ResourceObj.list(ResourceObj.java:117)
        at ngasi.caimito.CaimitoWebdavServlet.doPropfind(CaimitoWebdavServlet.java:738)
        at ngasi.caimito.CaimitoWebdavServlet.service(CaimitoWebdavServlet.java:398)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.shaft.ShaftFilter.doFilter(ShaftFilter.java:204)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:225)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:169)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:927)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:999)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:565)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:309)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
        at java.lang.Thread.run(Thread.java:679)

if I leave the version unset, I get ParseExceptions's - but I think this is a problem with our cloud

ngasi.caimito.CaimitoException: com.google.gson.JsonParseException: The JsonDeserializer com.google.gson.DefaultTypeAdapters$CollectionTypeAdapter@226e8504 failed to deserialized json object {} given the type com.google.gson.ParameterizedTypeImpl@7de53ec4
        at ngasi.caimito.CaimitoException.throwException(CaimitoException.java:56)
        at ngasi.caimito.resource.OpenStackResourceObj.auth(OpenStackResourceObj.java:525)
        at ngasi.caimito.resource.OpenStackResourceObj.doList(OpenStackResourceObj.java:535)
        at ngasi.caimito.resource.ResourceObj.list(ResourceObj.java:117)
        at ngasi.caimito.CaimitoWebdavServlet.doPropfind(CaimitoWebdavServlet.java:738)
        at ngasi.caimito.CaimitoWebdavServlet.service(CaimitoWebdavServlet.java:398)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.shaft.ShaftFilter.doFilter(ShaftFilter.java:204)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:225)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:169)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:927)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:999)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:565)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:309)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
        at java.lang.Thread.run(Thread.java:679)
ngasi.caimito.CaimitoException: com.google.gson.JsonParseException: The JsonDeserializer com.google.gson.DefaultTypeAdapters$CollectionTypeAdapter@226e8504 failed to deserialized json object {} given the type com.google.gson.ParameterizedTypeImpl@7de53ec4
        at ngasi.caimito.CaimitoException.throwException(CaimitoException.java:56)
        at ngasi.caimito.resource.OpenStackResourceObj.auth(OpenStackResourceObj.java:525)
        at ngasi.caimito.resource.OpenStackResourceObj.doList(OpenStackResourceObj.java:535)
        at ngasi.caimito.resource.ResourceObj.list(ResourceObj.java:117)
        at ngasi.caimito.CaimitoWebdavServlet.doPropfind(CaimitoWebdavServlet.java:738)
        at ngasi.caimito.CaimitoWebdavServlet.service(CaimitoWebdavServlet.java:398)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.shaft.ShaftFilter.doFilter(ShaftFilter.java:204)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:225)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:169)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:927)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:999)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:565)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:309)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
        at java.lang.Thread.run(Thread.java:679)

This one could be a problem with our cloud though  - the stuff that's coming back is a bit crap:

OST /v2.0/tokens HTTP/1.1
Content-type: application/json
Transfer-Encoding: chunked
Host: keystone.rc.nectar.org.au:5000
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.0.1 (java 1.5)
Expect: 100-Continue

69
{"auth":{"passwordCredentials":{"password":"[password]","username":"[username]"}}}
0

HTTP/1.1 200 OK
Content-Type: application/json
Vary: X-Auth-Token
Date: Mon, 18 Jun 2012 05:29:39 GMT
Transfer-Encoding: chunked
Connection: keep-alive

fa
{"access": {"token": {"expires": "2012-06-19T05:29:39Z", "id": "[token]"}, "serviceCatalog": {}, "user": {"username": "[username]", "roles_links": [], "id": "27", "roles": [], "name": "[username]"}}}
0

Let me look into it at our end first

**Comment by ngasiproj** [comment]
If I configure the api=2.0 I get a NullPointerException, and no request gets sent to swift
ngasi.caimito.CaimitoException: java.lang.NullPointerException

The above is fixed with latest Pull. However below does appear to be issue with your auth. Remember I think with V2 you no longer need to supply Tenant info when authenticating. And I no longer have access to the v2 account you had setup for me - so unable to test.

This one could be a problem with our cloud though - the stuff that's coming back is a bit crap:
OST /v2.0/tokens HTTP/1.1
Content-type: application/json
Transfer-Encoding: chunked
Host: keystone.rc.nectar.org.au:5000

**Comment by fifieldt** [comment]
OK, there isn't a problem in the cloud it turns out. It's an implementation change to keystone in Essex:

Here is what needs to happen:
do a POST to /tokens passing in username/password
That returns a token.
Use that token to do a post on /tenants
That returns your tenants
Then do a post on /tokens passing in token and tenantName

**Comment by ngasiproj** [comment]
Any chance I can get access to an Essex instance?
Regards

-----Original Message-----

**Comment by fifieldt** [comment]
sure - please give me a moment, unfortunately quite busy today

**Comment by fifieldt** [comment]
Essex is long deprecated. Let's close this issue :)
