### ISSUE TITLE
Error in current trunk / master

### ISSUE THREAD

**Issue by Sethur** [ngasiproj/caimito#8]
The last commit seams to have gone horribly wrong. Several files contain merge artifacts such as: 

<<<<<<< HEAD

This is in server.xml, web.xml, config.properties, etc.

**Comment by ngasiproj** [comment]
Hi Sethur,
Thanks for binging to my attention.
Give it another try please.
Regards

-----Original Message-----

**Comment by Sethur** [comment]
Hi,

strange that no one seems to have noticed that until know. I am relieved that this project is still maintained, we were really looking forward on a could storage webdav solution. Was trying to correct the errors from hand until now, but it did not work out.

Also, can you tell me how to properly include the tenant name for a openstack setup in config.properties? Do I have to add it to the username via a colon (:) separator? We are using Keystone V2 authentication.

Thanks,

Tristan

**Comment by Sethur** [comment]
Unfortunately, I am getting the same error as with my manually corrected trunk version. The server starts up fine and I can connect as superadmin, but something else seems to go wrong, possibly the connection to the SWIFT storage. I have set up a MySQL db for usage with caimito (which works fine, tables are created) and I put the tenancy name behind the user name, separated by ":"

# The error trace is:

Using CATALINA_BASE:   /srv/www/caimito
Using CATALINA_HOME:   /srv/www/caimito
Using CATALINA_TMPDIR: /srv/www/caimito/temp
Using JRE_HOME:        /usr/lib/jvm/default-java
Using CLASSPATH:       /srv/www/caimito/bin/bootstrap.jar:/srv/www/caimito/bin/tomcat-juli.jar
Oct 19, 2012 2:19:57 AM org.apache.catalina.core.AprLifecycleListener init
INFO: The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: /usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64/server:/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64:/usr/lib/jvm/java-6-openjdk-amd64/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib
Oct 19, 2012 2:19:58 AM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-bio-8619"]
Oct 19, 2012 2:19:58 AM org.apache.catalina.startup.Catalina load
INFO: Initialization processed in 694 ms
Oct 19, 2012 2:19:58 AM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Catalina
Oct 19, 2012 2:19:58 AM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/7.0.27
Oct 19, 2012 2:19:58 AM org.apache.catalina.startup.HostConfig deployDescriptor
INFO: Deploying configuration descriptor /srv/www/caimito/conf/Catalina/localhost/ROOT.xml
INIT SHAFT ASYNC FILTER v.4-b08142012A
Oct 19, 2012 2:19:59 AM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-bio-8619"]
Oct 19, 2012 2:19:59 AM org.apache.catalina.startup.Catalina start
INFO: Server startup in 1527 ms
 Caimito Version  0.9.1
 Failed V1 Auth java.lang.Exception: Get Method failed: HTTP/1.1 500 Internal Server Error
java.lang.Exception: Get Method failed: HTTP/1.1 500 Internal Server Error
        at tools.util.HttpClientUtil.trustNVGet(HttpClientUtil.java:1532)
        at tools.util.HttpClientUtil.trustGet(HttpClientUtil.java:1237)
        at tools.util.HttpClientUtil.trustGet(HttpClientUtil.java:1220)
        at tools.util.HttpClientUtil.trustGet(HttpClientUtil.java:1171)
        at tools.util.HttpClientUtil.trustGet(HttpClientUtil.java:953)
        at ngasi.caimito.resource.OpenStackResourceObj.auth(OpenStackResourceObj.java:623)
        at ngasi.caimito.resource.OpenStackResourceObj.auth(OpenStackResourceObj.java:510)
        at ngasi.caimito.resource.OpenStackResourceObj.doList(OpenStackResourceObj.java:723)
        at ngasi.caimito.resource.ResourceObj.list(ResourceObj.java:117)
        at ngasi.caimito.CaimitoDefaultServlet.renderHtml(CaimitoDefaultServlet.java:1635)
        at ngasi.caimito.CaimitoDefaultServlet.render(CaimitoDefaultServlet.java:1428)
        at ngasi.caimito.CaimitoDefaultServlet.serveResource(CaimitoDefaultServlet.java:1101)
        at ngasi.caimito.CaimitoDefaultServlet.doGet(CaimitoDefaultServlet.java:533)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
        at ngasi.caimito.CaimitoAsyncWebdavServlet.superService(CaimitoAsyncWebdavServlet.java:373)
        at ngasi.caimito.CaimitoAsyncWebdavServlet.performService(CaimitoAsyncWebdavServlet.java:418)
        at ngasi.caimito.CaimitoAsyncWebdavServlet$1.run(CaimitoAsyncWebdavServlet.java:456)
        at org.apache.catalina.core.AsyncContextImpl$RunnableWrapper.run(AsyncContextImpl.java:474)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
        at java.lang.Thread.run(Thread.java:679)
java.lang.Exception: HTTP/1.1 411 Length Required post Method failed: <html>
<head><title>411 Length Required</title></head>
<body bgcolor="white">
<center><h1>411 Length Required</h1></center>
<hr><center>nginx/1.1.19</center>
</body>
</html>

```
    at tools.util.HttpClientUtil.trustPost(HttpClientUtil.java:1903)
    at ngasi.caimito.resource.OpenStackResourceObj.authv2(OpenStackResourceObj.java:571)
    at ngasi.caimito.resource.OpenStackResourceObj.auth(OpenStackResourceObj.java:694)
    at ngasi.caimito.resource.OpenStackResourceObj.auth(OpenStackResourceObj.java:510)
    at ngasi.caimito.resource.OpenStackResourceObj.doList(OpenStackResourceObj.java:723)
    at ngasi.caimito.resource.ResourceObj.list(ResourceObj.java:117)
    at ngasi.caimito.CaimitoDefaultServlet.renderHtml(CaimitoDefaultServlet.java:1635)
    at ngasi.caimito.CaimitoDefaultServlet.render(CaimitoDefaultServlet.java:1428)
    at ngasi.caimito.CaimitoDefaultServlet.serveResource(CaimitoDefaultServlet.java:1101)
    at ngasi.caimito.CaimitoDefaultServlet.doGet(CaimitoDefaultServlet.java:533)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
    at ngasi.caimito.CaimitoAsyncWebdavServlet.superService(CaimitoAsyncWebdavServlet.java:373)
    at ngasi.caimito.CaimitoAsyncWebdavServlet.performService(CaimitoAsyncWebdavServlet.java:418)
    at ngasi.caimito.CaimitoAsyncWebdavServlet$1.run(CaimitoAsyncWebdavServlet.java:456)
    at org.apache.catalina.core.AsyncContextImpl$RunnableWrapper.run(AsyncContextImpl.java:474)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:679)
```

ngasi.caimito.CaimitoException: java.lang.Exception: HTTP/1.1 411 Length Required post Method failed: <html>
<head><title>411 Length Required</title></head>
<body bgcolor="white">
<center><h1>411 Length Required</h1></center>
<hr><center>nginx/1.1.19</center>
</body>
</html>

```
    at ngasi.caimito.CaimitoException.throwException(CaimitoException.java:56)
    at ngasi.caimito.resource.OpenStackResourceObj.auth(OpenStackResourceObj.java:713)
    at ngasi.caimito.resource.OpenStackResourceObj.auth(OpenStackResourceObj.java:510)
    at ngasi.caimito.resource.OpenStackResourceObj.doList(OpenStackResourceObj.java:723)
    at ngasi.caimito.resource.ResourceObj.list(ResourceObj.java:117)
    at ngasi.caimito.CaimitoDefaultServlet.renderHtml(CaimitoDefaultServlet.java:1635)
    at ngasi.caimito.CaimitoDefaultServlet.render(CaimitoDefaultServlet.java:1428)
    at ngasi.caimito.CaimitoDefaultServlet.serveResource(CaimitoDefaultServlet.java:1101)
    at ngasi.caimito.CaimitoDefaultServlet.doGet(CaimitoDefaultServlet.java:533)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
    at ngasi.caimito.CaimitoAsyncWebdavServlet.superService(CaimitoAsyncWebdavServlet.java:373)
    at ngasi.caimito.CaimitoAsyncWebdavServlet.performService(CaimitoAsyncWebdavServlet.java:418)
    at ngasi.caimito.CaimitoAsyncWebdavServlet$1.run(CaimitoAsyncWebdavServlet.java:456)
    at org.apache.catalina.core.AsyncContextImpl$RunnableWrapper.run(AsyncContextImpl.java:474)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:679)
```

javax.servlet.ServletException: Error accessing resource
        at ngasi.caimito.CaimitoDefaultServlet.renderHtml(CaimitoDefaultServlet.java:1688)
        at ngasi.caimito.CaimitoDefaultServlet.render(CaimitoDefaultServlet.java:1428)
        at ngasi.caimito.CaimitoDefaultServlet.serveResource(CaimitoDefaultServlet.java:1101)
        at ngasi.caimito.CaimitoDefaultServlet.doGet(CaimitoDefaultServlet.java:533)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
        at ngasi.caimito.CaimitoAsyncWebdavServlet.superService(CaimitoAsyncWebdavServlet.java:373)
        at ngasi.caimito.CaimitoAsyncWebdavServlet.performService(CaimitoAsyncWebdavServlet.java:418)
        at ngasi.caimito.CaimitoAsyncWebdavServlet$1.run(CaimitoAsyncWebdavServlet.java:456)
        at org.apache.catalina.core.AsyncContextImpl$RunnableWrapper.run(AsyncContextImpl.java:474)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
        at java.lang.Thread.run(Thread.java:679)
Caused by: ngasi.caimito.CaimitoException: java.lang.Exception: HTTP/1.1 411 Length Required post Method failed: <html>
<head><title>411 Length Required</title></head>
<body bgcolor="white">
<center><h1>411 Length Required</h1></center>
<hr><center>nginx/1.1.19</center>
</body>
</html>

```
    at ngasi.caimito.CaimitoException.throwException(CaimitoException.java:56)
    at ngasi.caimito.resource.OpenStackResourceObj.auth(OpenStackResourceObj.java:713)
    at ngasi.caimito.resource.OpenStackResourceObj.auth(OpenStackResourceObj.java:510)
    at ngasi.caimito.resource.OpenStackResourceObj.doList(OpenStackResourceObj.java:723)
    at ngasi.caimito.resource.ResourceObj.list(ResourceObj.java:117)
    at ngasi.caimito.CaimitoDefaultServlet.renderHtml(CaimitoDefaultServlet.java:1635)
    ... 11 more
```

# 

Any ideas?

**Comment by Sethur** [comment]
Update: I played around with the username to check if the colon or the fact that the username is an email address is a problem and changed it to a single word (which should just result in a authentication error, since I cannot change the username on the openstack side). Now I get another error trace (listed below). Am I using the wrong java version (openjdk-1.6-amd64)? I saw that somebody who posted here was also working with the same Australian OpenStack framework (NeCTAR, Keystone V2.0) that we are and got it to work somehow...

Using CATALINA_BASE:   /srv/www/caimito
Using CATALINA_HOME:   /srv/www/caimito
Using CATALINA_TMPDIR: /srv/www/caimito/temp
Using JRE_HOME:        /usr/lib/jvm/default-java
Using CLASSPATH:       /srv/www/caimito/bin/bootstrap.jar:/srv/www/caimito/bin/tomcat-juli.jar
Oct 19, 2012 2:30:08 AM org.apache.catalina.core.AprLifecycleListener init
INFO: The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: /usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64/server:/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64:/usr/lib/jvm/java-6-openjdk-amd64/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib
Oct 19, 2012 2:30:08 AM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-bio-8619"]
Oct 19, 2012 2:30:08 AM org.apache.catalina.startup.Catalina load
INFO: Initialization processed in 747 ms
Oct 19, 2012 2:30:08 AM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Catalina
Oct 19, 2012 2:30:08 AM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/7.0.27
Oct 19, 2012 2:30:08 AM org.apache.catalina.startup.HostConfig deployDescriptor
INFO: Deploying configuration descriptor /srv/www/caimito/conf/Catalina/localhost/ROOT.xml
INIT SHAFT ASYNC FILTER v.4-b08142012A
Oct 19, 2012 2:30:09 AM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-bio-8619"]
Oct 19, 2012 2:30:09 AM org.apache.catalina.startup.Catalina start
INFO: Server startup in 930 ms
 Caimito Version  0.9.1
java.lang.ArrayIndexOutOfBoundsException: 1
        at ngasi.caimito.resource.OpenStackResourceObj.authv2(OpenStackResourceObj.java:550)
        at ngasi.caimito.resource.OpenStackResourceObj.auth(OpenStackResourceObj.java:694)
        at ngasi.caimito.resource.OpenStackResourceObj.auth(OpenStackResourceObj.java:510)
        at ngasi.caimito.resource.OpenStackResourceObj.doList(OpenStackResourceObj.java:723)
        at ngasi.caimito.resource.ResourceObj.list(ResourceObj.java:117)
        at ngasi.caimito.CaimitoDefaultServlet.renderHtml(CaimitoDefaultServlet.java:1635)
        at ngasi.caimito.CaimitoDefaultServlet.render(CaimitoDefaultServlet.java:1428)
        at ngasi.caimito.CaimitoDefaultServlet.serveResource(CaimitoDefaultServlet.java:1101)
        at ngasi.caimito.CaimitoDefaultServlet.doGet(CaimitoDefaultServlet.java:533)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
        at ngasi.caimito.CaimitoAsyncWebdavServlet.superService(CaimitoAsyncWebdavServlet.java:373)
        at ngasi.caimito.CaimitoAsyncWebdavServlet.performService(CaimitoAsyncWebdavServlet.java:418)
        at ngasi.caimito.CaimitoAsyncWebdavServlet$1.run(CaimitoAsyncWebdavServlet.java:456)
        at org.apache.catalina.core.AsyncContextImpl$RunnableWrapper.run(AsyncContextImpl.java:474)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
        at java.lang.Thread.run(Thread.java:679)
ngasi.caimito.CaimitoException: java.lang.ArrayIndexOutOfBoundsException: 1
        at ngasi.caimito.CaimitoException.throwException(CaimitoException.java:56)
        at ngasi.caimito.resource.OpenStackResourceObj.auth(OpenStackResourceObj.java:713)
        at ngasi.caimito.resource.OpenStackResourceObj.auth(OpenStackResourceObj.java:510)
        at ngasi.caimito.resource.OpenStackResourceObj.doList(OpenStackResourceObj.java:723)
        at ngasi.caimito.resource.ResourceObj.list(ResourceObj.java:117)
        at ngasi.caimito.CaimitoDefaultServlet.renderHtml(CaimitoDefaultServlet.java:1635)
        at ngasi.caimito.CaimitoDefaultServlet.render(CaimitoDefaultServlet.java:1428)
        at ngasi.caimito.CaimitoDefaultServlet.serveResource(CaimitoDefaultServlet.java:1101)
        at ngasi.caimito.CaimitoDefaultServlet.doGet(CaimitoDefaultServlet.java:533)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
        at ngasi.caimito.CaimitoAsyncWebdavServlet.superService(CaimitoAsyncWebdavServlet.java:373)
        at ngasi.caimito.CaimitoAsyncWebdavServlet.performService(CaimitoAsyncWebdavServlet.java:418)
        at ngasi.caimito.CaimitoAsyncWebdavServlet$1.run(CaimitoAsyncWebdavServlet.java:456)
        at org.apache.catalina.core.AsyncContextImpl$RunnableWrapper.run(AsyncContextImpl.java:474)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
        at java.lang.Thread.run(Thread.java:679)
javax.servlet.ServletException: Error accessing resource
        at ngasi.caimito.CaimitoDefaultServlet.renderHtml(CaimitoDefaultServlet.java:1688)
        at ngasi.caimito.CaimitoDefaultServlet.render(CaimitoDefaultServlet.java:1428)
        at ngasi.caimito.CaimitoDefaultServlet.serveResource(CaimitoDefaultServlet.java:1101)
        at ngasi.caimito.CaimitoDefaultServlet.doGet(CaimitoDefaultServlet.java:533)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
        at ngasi.caimito.CaimitoAsyncWebdavServlet.superService(CaimitoAsyncWebdavServlet.java:373)
        at ngasi.caimito.CaimitoAsyncWebdavServlet.performService(CaimitoAsyncWebdavServlet.java:418)
        at ngasi.caimito.CaimitoAsyncWebdavServlet$1.run(CaimitoAsyncWebdavServlet.java:456)
        at org.apache.catalina.core.AsyncContextImpl$RunnableWrapper.run(AsyncContextImpl.java:474)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
        at java.lang.Thread.run(Thread.java:679)
Caused by: ngasi.caimito.CaimitoException: java.lang.ArrayIndexOutOfBoundsException: 1
        at ngasi.caimito.CaimitoException.throwException(CaimitoException.java:56)
        at ngasi.caimito.resource.OpenStackResourceObj.auth(OpenStackResourceObj.java:713)
        at ngasi.caimito.resource.OpenStackResourceObj.auth(OpenStackResourceObj.java:510)
        at ngasi.caimito.resource.OpenStackResourceObj.doList(OpenStackResourceObj.java:723)
        at ngasi.caimito.resource.ResourceObj.list(ResourceObj.java:117)
        at ngasi.caimito.CaimitoDefaultServlet.renderHtml(CaimitoDefaultServlet.java:1635)
        ... 11 more

**Comment by ngasiproj** [comment]
Hi Sethur,
Could you provide your server.properties (x out user/password etc).
Regards

-----Original Message-----

**Comment by Sethur** [comment]
Hi again and thx for the fast response,

some background info:

Ditro: Ubuntu 12.04 LTS, x64
Java: Openjdk, 1.6.0 x64
Base Directory: /srv/www/caimito

As i said, I tried both a long username with tenancy added and a short single word one, which led to different errors (see last posts).

Now posting config.properties and ROOT.xml:

---- config.properties ----

```
#cloud_accounts_for_administration_only
cloud.setup=single_cloud_account_with_single_storage
#minutes
request.timeout=130
#optional - 1.0,2.0
cloud.api.version=2.0


#file,openstack
resource=openstack
#A Container or Bucket
cloud.store=caimito
#cloud.username=first
cloud.username=first.last@uniname.edu.au:tenantName
cloud.api.key_password=xxxxxxxxxxxxxxxx

cloud.url=https://keystone.rc.nectar.org.au:5000/v2.0/

#public,internal
cloud.endpoint.access=public

#minutes
cloud.max_auth_interval=20
#Tue, 24 Apr 2012 00:05:15 GMT
cloud.obj.details.dateformat=EEE, dd MMM yyyy HH:mm:ss z
#2012-04-24T00:05:15.474470
#%Y-%m-%dT%H:%M:%S.000Z
cloud.date.remove.end=true
cloud.dateformat=yyyy-MM-dd'T'HH:mm:ss
#%Y-%m-%dT%H:%M:%S.000Z
#yyyy-MM-dd'T'HH:mm:ss.'Z'
maxspace.units=GB
file.resource.dir=/srv/www/caimito/drive
SecurityRealmName=Caimito
shaft.app=ca
resource.dir.listing=true
Microsoft-WebDAV-MiniRedir/6.1.7601.auth=digest
protectedRoot=true
cacheable=true
cachedir=/srv/www/caimito/cache
serverinfo=Caimito
CAIMITO_CSS=H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#FF8FC2;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#FF8FC2;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#FF8FC2;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#FF8FC2;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #FF8FC2;}
directory.title=Directory
directory.parent=Parent
directory.filename=Name
directory.size=Size
directory.lastModified=Date
```

----- end of config.properties -----

----- ROOT.xml -----

```
<Context path="/" docBase="/srv/www/caimito/webapps" crossContext="true">
<!--
<Resource name="jdbc/caimito" auth="Container" type="javax.sql.DataSource"
maxActive="200" maxIdle="20" maxWait="10000"
username="caimito" password="tiger" driverClassName="org.apache.derby.jdbc.EmbeddedDriver"
url="jdbc:derby:/usr/caimito/bin/caimito_db;create=true"/>
-->

<!-- MySQL -->
<Resource name="jdbc/caimito" auth="Container" type="javax.sql.DataSource"
maxActive="200" maxIdle="20" maxWait="10000" validationQuery="SELECT 1"  testOnBorrow="true"
username="caimito" password="yellowsmallbird" driverClassName="com.mysql.jdbc.Driver"
url="jdbc:mysql://localhost:3306/caimito?autoReconnect=true"/>

        <Resource
                name="mail/MailSession"
                auth="Container"
                type="javax.mail.Session"
                mail.transport.protocol="smtp"
                mail.smtp.host="localhost"
        />


</Context>
```

---- end of ROOT.xml ----

**Comment by ngasiproj** [comment]
The Stack trace "HTTP/1.1 500 Internal Server Error" shows an internal error to your OpenStack Server.
That is an internal error that you need to address. Check the OpenStack logs. I also noticed nginx - Is that a proxy?

-----Original Message-----

**Comment by Sethur** [comment]
Hi Gabe,

Unfortunately, I have no control over the OpenStack server. It's administered by an Australian Government Project called NeCTAR. However, I saw that one Caimito user (fifieldt) in here also seems to successfully use Caimito for NeCTAR SWIFT access (according to the thread in the closed issue about Keystone V2), so it should not be a problem on the OpenStack side. Nginx is afaik an alternative to Apache, i.e. mainly a HTTP server.

I will try to contact fifieldt for suggestions of how he got it running and also the NeCTAR support team (since they, in fact, pointed me to your very useful application).

Cheers,

Tristan

**Comment by ngasiproj** [comment]
Is nginx on your side or does it sit on NECTAR?

-----Original Message-----

**Comment by Sethur** [comment]
It seems to sit on NeCTAR since it is definitely not on my side. I am using Apache 2 at the same time for something else, but I stopped the server before trying Caimito so that cannot be the problem. I am currently setting up a post on the NeCTAR research cloud support forum to try to get Tom Fifield's attention who is in their administration team and apparently knows how you can get it to work.

Could it be that I have to set some different ACLs for my SWIFT container?
